[package]
name = "mixnet"
edition = "2021"
rust-version = "1.56.1"
description = "Mixnet protocol for libp2p"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/paritytech/substrate"
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
instant = "0.1.12"
libp2p-core = { version = "0.37.0", default-features = false }
libp2p-swarm = "0.40.1"
log = "0.4.17"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
void = "1.0"
blake2 = { version = "0.10.4", default-features = false }
curve25519-dalek = "3.2.0"
dyn-clone = "1.0.5"
static_assertions = "1.1.0"
bytemuck = "1.12.3"
ambassador = "0.3.5"

#sphinx deps
x25519-dalek = "1.1.1"
aes = "0.8.2"
ctr = "0.9.2"
sha2 = "0.10.2"
hkdf = "0.12.3"
hmac = "0.12.1"
lioness = "0.1.2"
subtle = "2.4.1"

[dev-dependencies]
async-std = "1.12"
libp2p-tcp = {version = "0.37.0", features = ["async-io"]}
libp2p-noise = "0.40.0"
libp2p-yamux = "0.41.0"
libp2p-mplex = "0.37.0"
env_logger = "0.9.0"
ed25519-zebra = "3.1.0"
parking_lot = { version = "0.12" }
